### PR TITLE
flask backend

### PR DESCRIPTION
**Pull request by EricEisaman**

### CODE REVIEW

**Comment by EricEisaman** [comment]
Basic React hooks test added.

**Comment by EricEisaman** [comment]
Needs production start script in package.json.

**Comment by EricEisaman** [comment]
I should probably change the proxy reference to the production domain.
I think it should deploy at that point.

https://github.com/MainersMatter/pledge2protect/blob/develop/package.json#L38

**Comment by EricEisaman** [comment]
[Local Performance](https://drive.google.com/uc?export=view&id=1QGwotwkkET3xdD5rtFJ9IUelY0OVMFeM)

**Comment by erin-doyle** [comment]
This is great but I'm going to go ahead and close this PR as we don't want to merge this into master at this time.

**Pull request closed without merging**
